/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://travauxcentre.fr",
  generateRobotsTxt: true,
  sitemapSize: 1000,
  changefreq: "weekly",
  priority: 0.7,
  additionalPaths: async () => [
    { loc: "/",                                  priority: 1.0,  changefreq: "weekly" },
    { loc: "/services",                          priority: 0.9,  changefreq: "monthly" },
    { loc: "/services/renovation-interieure",   priority: 0.9,  changefreq: "monthly" },
    { loc: "/services/gros-oeuvre",             priority: 0.9,  changefreq: "monthly" },
    { loc: "/services/amenagement-exterieur",   priority: 0.9,  changefreq: "monthly" },
    { loc: "/services/second-oeuvre",           priority: 0.9,  changefreq: "monthly" },
    { loc: "/realisations",                     priority: 0.8,  changefreq: "weekly" },
    { loc: "/a-propos",                         priority: 0.7,  changefreq: "monthly" },
    { loc: "/contact",                          priority: 0.8,  changefreq: "monthly" },
    { loc: "/devis",                            priority: 0.95, changefreq: "monthly" },
    { loc: "/rendez-vous",                                   priority: 0.85, changefreq: "monthly" },
    { loc: "/zones-intervention",                               priority: 0.9,  changefreq: "monthly" },
    // Zones < 20 km
    { loc: "/zones-intervention/saint-omer",                  priority: 0.85, changefreq: "monthly" },
    { loc: "/zones-intervention/lumbres",                     priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/fauquembergues",              priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/aire-sur-la-lys",             priority: 0.8,  changefreq: "monthly" },
    // Zones 20–45 km
    { loc: "/zones-intervention/ardres",                      priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/fruges",                      priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/desvres",                     priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/hazebrouck",                  priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/lillers",                     priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/marquise",                    priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/hesdin",                      priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/bruay-la-buissiere",          priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/calais",                      priority: 0.85, changefreq: "monthly" },
    { loc: "/zones-intervention/etaples",                     priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/montreuil-sur-mer",           priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/saint-pol-sur-ternoise",      priority: 0.8,  changefreq: "monthly" },
    // Zones 45–80 km
    { loc: "/zones-intervention/le-touquet",                  priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/bethune",                     priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/gravelines",                  priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/berck",                       priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/lens",                        priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/arras",                       priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/henin-beaumont",              priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/dunkerque",                   priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/lille",                       priority: 0.8,  changefreq: "monthly" },
    { loc: "/zones-intervention/doullens",                    priority: 0.75, changefreq: "monthly" },
  ],
  robotsTxtOptions: {
    policies: [
      { userAgent: "*", allow: "/" },
      { userAgent: "*", disallow: ["/api/", "/dashboard/", "/auth/", "/onboarding/"] },
    ],
  },
}
